// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh4ZEZrypYKbLpX4wzkFEmdiDmTF2psjs',
    appId: '1:906950790483:web:85442eaac32f10af5c25a6',
    messagingSenderId: '906950790483',
    projectId: 'abdumomin6791',
    authDomain: 'abdumomin6791.firebaseapp.com',
    storageBucket: 'abdumomin6791.firebasestorage.app',
    measurementId: 'G-PHSXGQK86R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOTL_doTZuODKDdWkUnhBUAArz3Aa25xE',
    appId: '1:906950790483:android:e96f1d62ce5ec1605c25a6',
    messagingSenderId: '906950790483',
    projectId: 'abdumomin6791',
    storageBucket: 'abdumomin6791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8z_MgnUjSQlRHnJ-fAFDeIjpvDbkheBk',
    appId: '1:906950790483:ios:d5e38d8a55b46bd05c25a6',
    messagingSenderId: '906950790483',
    projectId: 'abdumomin6791',
    storageBucket: 'abdumomin6791.firebasestorage.app',
    iosBundleId: 'uz.gita.flutterBookApp',
  );
}
